polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),  # Главная страница приложения polls, список опросов
    path('<int:poll_id>/', views.poll_detail, name='poll_detail'),  # Подробная страница опроса, с первым вопросом или сообщением об отсутствии вопросов
    path('question/<int:question_id>/', views.question_view, name='question_view'),  # Представление для отображения вопроса и приема ответа
    path('<int:poll_id>/results/', views.results, name='results'),  # Страница с результатами опроса
    path('response/<int:question_id>/', views.save_response, name='save_response'),
]

polls_app/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),  # Подключение urls из приложения polls
]

polls/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.text


class AnswerOption(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answer_options')
    text = models.CharField(max_length=200)
    next_question = models.ForeignKey('Question', on_delete=models.SET_NULL, null=True, blank=True, related_name='next_question_options')

    def __str__(self):
        return self.text


class Response(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_option = models.ForeignKey(AnswerOption, on_delete=models.CASCADE)
    user_id = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.user_id} - {self.question.text}"

polls/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.db import connection
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import ResponseForm
from .models import Poll, Question, AnswerOption, Response
import uuid

# Главная страница с перечнем опросов
def index(request):
    latest_poll_list = Poll.objects.all().order_by('-start_date')[:5]  # Показать последние 5 опросов
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)


# Пример функции для сохранения ответов пользователя
def save_response(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        # Генерируем уникальный идентификатор для пользователя
        # в реальном проекте реализовал бы сессии или куки
        user_id = str(uuid.uuid4())

        try:
            selected_option = question.answer_options.get(pk=request.POST['answer'])
            new_response = Response(question=question, answer_option=selected_option, user_id=user_id)  # Замените "temporary_user_id" на вашу логику идентификации пользователя
            new_response.save()

            # Проверяем, есть ли следующий вопрос на основе выбранного ответа
            if selected_option.next_question:
                # Если есть следующий вопрос, перенаправляем на него
                return HttpResponseRedirect(reverse('polls:question_view', args=(selected_option.next_question.id,)))
            else:
                # Если следующего вопроса нет, значит, это был последний вопрос опроса
                # Перенаправляем на страницу с результатами опроса
                return HttpResponseRedirect(reverse('polls:results', args=(question.poll.id,)))
        except (KeyError, AnswerOption.DoesNotExist):
            # Обрабатываем ошибку: выбранный ответ не существует или не был выбран
            return render(request, 'polls/question_detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
    else:
        # Если метод не POST, возвращаем пользователя на страницу текущего вопроса
        return redirect('polls:question_view', question_id=question_id)


# Подробное представление опроса с вопросами
def poll_detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    questions = poll.question_set.all().order_by('order')
    if not questions:
        return render(request, 'polls/no_questions.html', {'poll': poll})
    else:
        first_question = questions[0]
        return redirect('polls:question_view', question_id=first_question.id)


# Представление вопроса с формой для ответа
def question_view(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = ResponseForm(request.POST, question_id=question_id)
        if form.is_valid():
            response = form.save(commit=False)
            response.question = question
            response.user_id = str(uuid.uuid4())
            response.save()
            next_question = get_next_question(question, response.answer_option)
            if next_question:
                return redirect('polls:question_view', question_id=next_question.id)
            else:
                return redirect('polls:results', poll_id=question.poll.id)
    else:
        form = ResponseForm(question_id=question_id)
    return render(request, 'polls/question_detail.html', {'question': question, 'form': form})


# Логика для получения следующего вопроса
def get_next_question(current_question, selected_option):
    return selected_option.next_question


def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        with connection.cursor() as cursor:
            # Получаем общее количество участников опроса и данные по вопросам и ответам одним запросом
            cursor.execute("""
            SELECT 
                q.id, q.text,
                COUNT(DISTINCT r.user_id) AS responses_count,
                a.text AS answer_text,
                COUNT(r.id) AS answer_count,
                CAST(COUNT(r.id) AS FLOAT) * 100 / (SELECT COUNT(*) FROM polls_response WHERE question_id IN (SELECT id FROM polls_question WHERE poll_id = %s)) AS percentage
            FROM polls_question q
            LEFT JOIN polls_response r ON q.id = r.question_id
            LEFT JOIN polls_answeroption a ON r.answer_option_id = a.id
            WHERE q.poll_id = %s
            GROUP BY q.id, a.id
            ORDER BY responses_count DESC, q.id, a.id
            """, [poll_id, poll_id])

            questions_data = cursor.fetchall()

            current_responses_count = None
            rank = 0
            tie_rank_increment = 1

            questions = {}
            for row in questions_data:
                question_id, question_text, responses_count, answer_text, answer_count, percentage = row

                if question_id not in questions:
                    # Проверяем, нужно ли увеличивать ранг
                    if responses_count != current_responses_count:
                        rank += tie_rank_increment
                        current_responses_count = responses_count
                        tie_rank_increment = 1  # Сбрасываем счетчик повторений ранга
                    else:
                        tie_rank_increment += 1  # Несколько вопросов имеют одинаковое кол-во ответов

                    questions[question_id] = {
                        'rank': rank,
                        'text': question_text,
                        'responses_count': responses_count,
                        'answers': []
                    }
                if answer_text:  # Некоторые вопросы могут не иметь ответов
                    questions[question_id]['answers'].append({
                        'text': answer_text,
                        'count': answer_count,
                        'percentage': percentage
                    })

            context = {
                'poll': poll,
                'questions': list(questions.values())
            }

        return render(request, 'polls/results.html', context)

    except Poll.DoesNotExist:
        raise Http404("Poll does not exist")

polls/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/styles.css' %}">

</head>
<body>
    <header>
        <h1>{% block header %}{% endblock %}</h1>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p> Polls, 2024</p>
    </footer>
</body>
</html>

polls/templates/polls/index.html
{% extends "base.html" %}

{% block title %}Available Polls{% endblock %}

{% block header %}Available Polls{% endblock %}

{% block content %}
    <ul>
        {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:poll_detail' poll.id %}">{{ poll.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/no_questions.html
{% extends "base.html" %}

{% block title %}No Questions{% endblock %}

{% block header %}No Questions in {{ poll.title }}{% endblock %}

{% block content %}
    <p>There are no questions available for this poll.</p>
{% endblock %}

polls/templates/polls/question_detail.html
{% extends "base.html" %}

{% block title %}Question{% endblock %}

{% block header %}{{ question.text }}{% endblock %}

{% block content %}
  <form action="{% url 'polls:save_response' question.id %}" method="post">
    {% csrf_token %}
    {% for answer in question.answer_options.all %}
      <label>
        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
        {{ answer.text }}
      </label><br>
    {% endfor %}
    <input type="submit" value="Submit">
  </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block title %}Results for {{ poll.title }}{% endblock %}

{% block header %}Results for "{{ poll.title }}"{% endblock %}

{% block content %}
    <div class="poll-results">
        {% for question in questions %}
            <div class="question">
                <h3>{{ question.rank }}. {{ question.text }}</h3>
                <p>Total responses: {{ question.responses_count }}</p>
                <ul>
                    {% for answer in question.answers %}
                        <li>{{ answer.text }}: {{ answer.count }} votes ({{ answer.percentage|floatformat:2 }}%)</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
</head>
<body>
    <h1>Добро пожаловать на наш сайт!</h1>
    <p><a href="/polls/">Перейти к опросам</a></p>
</body>
</html>